-- Persistencia aislada del diario de decisiones simulado.
-- No reutiliza ni modifica operations, portfolio_snapshots o analysis_snapshots.

create table if not exists public.paper_simulations (
    id bigint generated by default as identity primary key,
    owner text not null,
    name text not null,
    status text not null default 'active'
        check (status in ('active', 'paused', 'archived')),
    base_currency text not null default 'EUR'
        check (char_length(base_currency) = 3),
    benchmark_ticker text not null default 'SPY',
    strategy_key text not null,
    engine_version text not null,
    start_date date not null,
    initial_nav_eur double precision not null check (initial_nav_eur > 0),
    initial_cash_eur double precision not null default 0
        check (initial_cash_eur >= 0),
    source_snapshot_date date,
    assumptions_json jsonb not null default '{}'::jsonb,
    initial_positions_json jsonb not null default '[]'::jsonb,
    recorded_by text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (initial_cash_eur <= initial_nav_eur),
    check (jsonb_typeof(assumptions_json) = 'object'),
    check (jsonb_typeof(initial_positions_json) = 'array'),
    constraint paper_simulations_owner_id_unique unique (owner, id)
);

create index if not exists paper_simulations_owner_status_date_idx
    on public.paper_simulations (owner, status, start_date desc, id desc);

alter table public.paper_simulations enable row level security;
revoke all on table public.paper_simulations from anon, authenticated;
grant all on table public.paper_simulations to service_role;
grant usage, select on sequence public.paper_simulations_id_seq to service_role;

create table if not exists public.paper_daily_runs (
    id bigint generated by default as identity primary key,
    owner text not null,
    simulation_id bigint not null,
    market_date date not null,
    signal_as_of timestamptz,
    input_hash text not null,
    status text not null default 'complete'
        check (status in ('complete', 'partial', 'failed')),
    proposed_actions_json jsonb not null default '[]'::jsonb,
    executed_actions_json jsonb not null default '[]'::jsonb,
    positions_after_json jsonb not null default '[]'::jsonb,
    cash_eur double precision not null check (cash_eur >= 0),
    net_nav_eur double precision not null check (net_nav_eur >= 0),
    hold_nav_eur double precision not null check (hold_nav_eur >= 0),
    benchmark_nav_eur double precision not null check (benchmark_nav_eur >= 0),
    realized_pnl_eur double precision not null default 0,
    unrealized_pnl_eur double precision not null default 0,
    cumulative_costs_eur double precision not null default 0
        check (cumulative_costs_eur >= 0),
    tax_reserve_eur double precision not null default 0
        check (tax_reserve_eur >= 0),
    coverage_pct double precision not null default 0
        check (coverage_pct between 0 and 100),
    warnings_json jsonb not null default '[]'::jsonb,
    rejected_json jsonb not null default '[]'::jsonb,
    engine_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint paper_daily_runs_owner_simulation_date_unique
        unique (owner, simulation_id, market_date),
    constraint paper_daily_runs_owner_simulation_fk
        foreign key (owner, simulation_id)
        references public.paper_simulations (owner, id)
        on delete cascade,
    check (jsonb_typeof(proposed_actions_json) = 'array'),
    check (jsonb_typeof(executed_actions_json) = 'array'),
    check (jsonb_typeof(positions_after_json) = 'array'),
    check (jsonb_typeof(warnings_json) = 'array'),
    check (jsonb_typeof(rejected_json) = 'array')
);

create index if not exists paper_daily_runs_owner_simulation_date_idx
    on public.paper_daily_runs (owner, simulation_id, market_date desc, id desc);

alter table public.paper_daily_runs enable row level security;
revoke all on table public.paper_daily_runs from anon, authenticated;
grant all on table public.paper_daily_runs to service_role;
grant usage, select on sequence public.paper_daily_runs_id_seq to service_role;
