-- Ejecutar una vez en Supabase > SQL Editor para activar Civislend/Segofactoring.
create table if not exists public.private_investments (
    id bigint generated by default as identity primary key,
    owner text not null,
    platform text not null check (platform in ('Civislend', 'Segofactoring')),
    project_name text not null,
    invested_amount double precision not null check (invested_amount > 0),
    current_value double precision not null check (current_value >= 0),
    expected_return_pct double precision not null default 0,
    start_date timestamptz not null,
    maturity_date timestamptz,
    status text not null default 'Activa'
        check (status in ('Activa', 'Finalizada', 'Retrasada', 'Impagada')),
    notes text not null default '',
    recorded_by text not null default '',
    created_at timestamptz not null default now(),
    check (maturity_date is null or maturity_date >= start_date)
);

create index if not exists private_investments_owner_start_idx
    on public.private_investments (owner, start_date desc, id desc);

alter table public.private_investments enable row level security;
revoke all on table public.private_investments from anon, authenticated;
grant all on table public.private_investments to service_role;
grant usage, select on sequence public.private_investments_id_seq to service_role;
