-- Crea las cuentas agregadas y añade las cinco plataformas provisionales de ddriu.
create table if not exists public.portfolio_accounts (
    id bigint generated by default as identity primary key,
    owner text not null,
    account_name text not null,
    account_type text not null
        check (account_type in ('Bróker', 'Inversión alternativa')),
    investments_value double precision not null default 0
        check (investments_value >= 0),
    cash_balance double precision not null default 0 check (cash_balance >= 0),
    currency text not null default 'EUR' check (char_length(currency) = 3),
    status text not null default 'Pendiente de actualizar'
        check (status in ('Pendiente de actualizar', 'Actualizada', 'Inactiva')),
    notes text not null default '',
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint portfolio_accounts_owner_name_unique unique (owner, account_name)
);

create index if not exists portfolio_accounts_owner_name_idx
    on public.portfolio_accounts (owner, account_name);

alter table public.portfolio_accounts enable row level security;
revoke all on table public.portfolio_accounts from anon, authenticated;
grant all on table public.portfolio_accounts to service_role;
grant usage, select on sequence public.portfolio_accounts_id_seq to service_role;

insert into public.portfolio_accounts (
    owner, account_name, account_type, investments_value, cash_balance,
    currency, status, notes
) values
    ('ddriu', 'MyInvestor', 'Bróker', 0, 0, 'EUR', 'Pendiente de actualizar',
        'Cuenta provisional: faltan posiciones e importes.'),
    ('ddriu', 'Trade Republic', 'Bróker', 0, 0, 'EUR', 'Pendiente de actualizar',
        'Cuenta provisional: faltan posiciones e importes.'),
    ('ddriu', 'Revolut', 'Bróker', 0, 0, 'EUR', 'Pendiente de actualizar',
        'Cuenta provisional: faltan posiciones e importes.'),
    ('ddriu', 'Segofactoring', 'Inversión alternativa', 0, 0, 'EUR',
        'Pendiente de actualizar', 'Cuenta provisional: faltan proyectos e importes.'),
    ('ddriu', 'Civislend', 'Inversión alternativa', 0, 0, 'EUR',
        'Pendiente de actualizar', 'Cuenta provisional: faltan proyectos e importes.')
on conflict (owner, account_name) do nothing;

select account_name, account_type, investments_value, cash_balance, currency, status
from public.portfolio_accounts
where owner = 'ddriu'
order by case account_name
    when 'MyInvestor' then 1
    when 'Trade Republic' then 2
    when 'Revolut' then 3
    when 'Segofactoring' then 4
    when 'Civislend' then 5
    else 6
end;
