-- Fotografías históricas de posiciones. No representan órdenes ni compraventas.
create table if not exists public.portfolio_snapshots (
    id bigint generated by default as identity primary key,
    owner text not null,
    snapshot_date date not null,
    platform text not null,
    asset_name text not null,
    raw_identifier text not null default '',
    analysis_ticker text not null default '',
    asset_type text not null default '',
    portfolio_block text not null default '',
    quantity double precision check (quantity is null or quantity >= 0),
    current_price double precision check (current_price is null or current_price >= 0),
    currency text not null default 'EUR' check (char_length(currency) = 3),
    value_eur double precision not null check (value_eur >= 0),
    return_pct double precision,
    cost_estimate_eur double precision
        check (cost_estimate_eur is null or cost_estimate_eur >= 0),
    gain_loss_eur double precision,
    comments text not null default '',
    source text not null default '',
    notes text not null default '',
    recorded_by text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint portfolio_snapshots_identity_unique
        unique (owner, snapshot_date, platform, asset_name)
);

create index if not exists portfolio_snapshots_owner_date_idx
    on public.portfolio_snapshots (owner, snapshot_date desc, platform, asset_name);

alter table public.portfolio_snapshots enable row level security;
revoke all on table public.portfolio_snapshots from anon, authenticated;
grant all on table public.portfolio_snapshots to service_role;
grant usage, select on sequence public.portfolio_snapshots_id_seq to service_role;

