-- Ejecutar una sola vez en Supabase > SQL Editor.
-- La aplicación utiliza una clave secreta sólo en el servidor de Streamlit.

create table if not exists public.operations (
    id bigint generated by default as identity primary key,
    owner text not null,
    ticker text not null,
    account_name text not null default '',
    side text not null check (side in ('Compra', 'Venta')),
    quantity double precision not null check (quantity > 0),
    price double precision not null check (price > 0),
    fees double precision not null default 0 check (fees >= 0),
    settlement_amount_eur double precision
        check (settlement_amount_eur is null or settlement_amount_eur > 0),
    fee_eur double precision check (fee_eur is null or fee_eur >= 0),
    fx_rate_to_eur double precision check (fx_rate_to_eur is null or fx_rate_to_eur > 0),
    executed_at timestamptz not null,
    notes text not null default '',
    currency text not null default 'EUR' check (char_length(currency) = 3),
    recorded_by text not null default '',
    created_at timestamptz not null default now()
);

-- Migración segura para instalaciones creadas con una versión anterior.
alter table public.operations
    add column if not exists recorded_by text not null default '';

alter table public.operations
    add column if not exists account_name text not null default '',
    add column if not exists settlement_amount_eur double precision,
    add column if not exists fee_eur double precision,
    add column if not exists fx_rate_to_eur double precision;

create index if not exists operations_owner_executed_idx
    on public.operations (owner, executed_at desc, id desc);

alter table public.operations enable row level security;

-- No se concede acceso a claves públicas. La clave secreta del backend usa
-- service_role y omite RLS; la app filtra siempre por el usuario autenticado.
revoke all on table public.operations from anon, authenticated;
grant all on table public.operations to service_role;
grant usage, select on sequence public.operations_id_seq to service_role;

create table if not exists public.favorites (
    id bigint generated by default as identity primary key,
    owner text not null,
    ticker text not null,
    name text not null default '',
    exchange text not null default '',
    tags text not null default '',
    recorded_by text not null default '',
    created_at timestamptz not null default now(),
    constraint favorites_owner_ticker_unique unique (owner, ticker)
);

alter table public.favorites
    add column if not exists tags text not null default '';

create index if not exists favorites_owner_name_idx
    on public.favorites (owner, name, ticker);

alter table public.favorites enable row level security;
revoke all on table public.favorites from anon, authenticated;
grant all on table public.favorites to service_role;
grant usage, select on sequence public.favorites_id_seq to service_role;

create table if not exists public.analysis_snapshots (
    id bigint generated by default as identity primary key,
    owner text not null,
    ticker text not null,
    analyzed_at timestamptz not null,
    price double precision not null check (price > 0),
    opportunity_score integer not null check (opportunity_score between 0 and 100),
    company_score integer check (company_score between 0 and 100),
    entry_score integer not null check (entry_score between 0 and 100),
    valuation_score integer check (valuation_score between 0 and 100),
    relative_score integer check (relative_score between 0 and 100),
    risk_score integer check (risk_score between 0 and 100),
    opportunity_label text not null default '',
    entry_label text not null default '',
    position_label text not null default '',
    expected_return_pct double precision,
    positive_rate_pct double precision
        check (positive_rate_pct between 0 and 100),
    expected_price double precision check (expected_price > 0),
    horizon_days integer check (horizon_days > 0),
    sector text not null default '',
    explanation text not null default '',
    note text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists analysis_snapshots_owner_ticker_date_idx
    on public.analysis_snapshots (owner, ticker, analyzed_at desc, id desc);

alter table public.analysis_snapshots enable row level security;
revoke all on table public.analysis_snapshots from anon, authenticated;
grant all on table public.analysis_snapshots to service_role;
grant usage, select on sequence public.analysis_snapshots_id_seq to service_role;

-- Inversiones no cotizadas introducidas manualmente por cada usuario. La app
-- sólo muestra esta sección en la cartera privada de ddriu.
create table if not exists public.private_investments (
    id bigint generated by default as identity primary key,
    owner text not null,
    platform text not null check (platform in ('Civislend', 'Segofactoring')),
    project_name text not null,
    invested_amount double precision not null check (invested_amount > 0),
    current_value double precision not null check (current_value >= 0),
    expected_return_pct double precision not null default 0,
    start_date timestamptz not null,
    maturity_date timestamptz,
    status text not null default 'Activa'
        check (status in ('Activa', 'Finalizada', 'Retrasada', 'Impagada')),
    notes text not null default '',
    recorded_by text not null default '',
    created_at timestamptz not null default now(),
    check (maturity_date is null or maturity_date >= start_date)
);

create index if not exists private_investments_owner_start_idx
    on public.private_investments (owner, start_date desc, id desc);

alter table public.private_investments enable row level security;
revoke all on table public.private_investments from anon, authenticated;
grant all on table public.private_investments to service_role;
grant usage, select on sequence public.private_investments_id_seq to service_role;

create table if not exists public.portfolio_accounts (
    id bigint generated by default as identity primary key,
    owner text not null,
    account_name text not null,
    account_type text not null
        check (account_type in ('Bróker', 'Inversión alternativa')),
    investments_value double precision not null default 0
        check (investments_value >= 0),
    cash_balance double precision not null default 0 check (cash_balance >= 0),
    currency text not null default 'EUR' check (char_length(currency) = 3),
    status text not null default 'Pendiente de actualizar'
        check (status in ('Pendiente de actualizar', 'Actualizada', 'Inactiva')),
    notes text not null default '',
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint portfolio_accounts_owner_name_unique unique (owner, account_name)
);

create index if not exists portfolio_accounts_owner_name_idx
    on public.portfolio_accounts (owner, account_name);

alter table public.portfolio_accounts enable row level security;
revoke all on table public.portfolio_accounts from anon, authenticated;
grant all on table public.portfolio_accounts to service_role;
grant usage, select on sequence public.portfolio_accounts_id_seq to service_role;

-- Fotografías históricas de posiciones. Se mantienen separadas de las operaciones
-- porque una valoración de bróker no prueba fecha, cantidad ni precio de compra.
create table if not exists public.portfolio_snapshots (
    id bigint generated by default as identity primary key,
    owner text not null,
    snapshot_date date not null,
    platform text not null,
    asset_name text not null,
    raw_identifier text not null default '',
    analysis_ticker text not null default '',
    asset_type text not null default '',
    portfolio_block text not null default '',
    quantity double precision check (quantity is null or quantity >= 0),
    current_price double precision check (current_price is null or current_price >= 0),
    currency text not null default 'EUR' check (char_length(currency) = 3),
    value_eur double precision not null check (value_eur >= 0),
    return_pct double precision,
    cost_estimate_eur double precision
        check (cost_estimate_eur is null or cost_estimate_eur >= 0),
    gain_loss_eur double precision,
    comments text not null default '',
    source text not null default '',
    notes text not null default '',
    recorded_by text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint portfolio_snapshots_identity_unique
        unique (owner, snapshot_date, platform, asset_name)
);

create index if not exists portfolio_snapshots_owner_date_idx
    on public.portfolio_snapshots (owner, snapshot_date desc, platform, asset_name);

alter table public.portfolio_snapshots enable row level security;
revoke all on table public.portfolio_snapshots from anon, authenticated;
grant all on table public.portfolio_snapshots to service_role;
grant usage, select on sequence public.portfolio_snapshots_id_seq to service_role;

-- Preferencias privadas de avisos. El correo sólo es accesible para el backend
-- mediante la clave secreta y nunca se expone a las claves públicas.
create table if not exists public.email_alert_preferences (
    owner text primary key,
    email text not null default '',
    enabled boolean not null default false,
    alert_buy boolean not null default true,
    alert_reduce boolean not null default true,
    alert_sell boolean not null default true,
    include_group boolean not null default true,
    minimum_buy_score integer not null default 65
        check (minimum_buy_score between 55 and 100),
    only_changes boolean not null default true,
    updated_at timestamptz not null default now()
);

alter table public.email_alert_preferences enable row level security;
revoke all on table public.email_alert_preferences from anon, authenticated;
grant all on table public.email_alert_preferences to service_role;

-- Último estado técnico visto por usuario y ticker. Permite avisar sólo cuando
-- cambia la señal y no repetir el mismo mensaje cada mañana.
create table if not exists public.email_alert_states (
    owner text not null,
    ticker text not null,
    signature text not null,
    entry_score integer not null check (entry_score between 0 and 100),
    entry_label text not null default '',
    position_label text not null default '',
    price double precision not null check (price > 0),
    evaluated_at timestamptz not null,
    notified_at timestamptz,
    company_name text not null default '',
    growth_score integer check (growth_score between 0 and 100),
    fundamental_score integer check (fundamental_score between 0 and 100),
    opportunity_score integer check (opportunity_score between 0 and 100),
    opportunity_status text not null default '',
    data_note text not null default '',
    primary key (owner, ticker)
);

alter table public.email_alert_states
    add column if not exists company_name text not null default '',
    add column if not exists growth_score integer,
    add column if not exists fundamental_score integer,
    add column if not exists opportunity_score integer,
    add column if not exists opportunity_status text not null default '',
    add column if not exists data_note text not null default '';

create index if not exists email_alert_states_owner_evaluated_idx
    on public.email_alert_states (owner, evaluated_at desc);

alter table public.email_alert_states enable row level security;
revoke all on table public.email_alert_states from anon, authenticated;
grant all on table public.email_alert_states to service_role;
