-- Ejecutar una sola vez en Supabase > SQL Editor.
-- La aplicación utiliza una clave secreta sólo en el servidor de Streamlit.

create table if not exists public.operations (
    id bigint generated by default as identity primary key,
    owner text not null,
    ticker text not null,
    side text not null check (side in ('Compra', 'Venta')),
    quantity double precision not null check (quantity > 0),
    price double precision not null check (price > 0),
    fees double precision not null default 0 check (fees >= 0),
    executed_at timestamptz not null,
    notes text not null default '',
    currency text not null default 'EUR' check (char_length(currency) = 3),
    recorded_by text not null default '',
    created_at timestamptz not null default now()
);

-- Migración segura para instalaciones creadas con una versión anterior.
alter table public.operations
    add column if not exists recorded_by text not null default '';

create index if not exists operations_owner_executed_idx
    on public.operations (owner, executed_at desc, id desc);

alter table public.operations enable row level security;

-- No se concede acceso a claves públicas. La clave secreta del backend usa
-- service_role y omite RLS; la app filtra siempre por el usuario autenticado.
revoke all on table public.operations from anon, authenticated;
grant all on table public.operations to service_role;
grant usage, select on sequence public.operations_id_seq to service_role;

create table if not exists public.favorites (
    id bigint generated by default as identity primary key,
    owner text not null,
    ticker text not null,
    name text not null default '',
    exchange text not null default '',
    recorded_by text not null default '',
    created_at timestamptz not null default now(),
    constraint favorites_owner_ticker_unique unique (owner, ticker)
);

create index if not exists favorites_owner_name_idx
    on public.favorites (owner, name, ticker);

alter table public.favorites enable row level security;
revoke all on table public.favorites from anon, authenticated;
grant all on table public.favorites to service_role;
grant usage, select on sequence public.favorites_id_seq to service_role;
